version: "2.1"

services:
  ic-postgres:
    image: ic-postgres
    container_name: ic-postgres
    ports:
      - 5432:5432
    restart: on-failure
    build: ./env/PostgreSQL
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./env/PostgreSQL/init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 15
    networks:
      - ic-network

  ic-rabbitmq:
    image: ic-rabbitmq
    container_name: ic-rabbitmq
    restart: on-failure
    build: ./env/RabbitMQ
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping", "-q"]
      interval: 5s
      timeout: 2s
      retries: 15
    networks:
      - ic-network

  ic-keycloak:
    image: ic-keycloak
    container_name: ic-keycloak
    build: ./env/KeyCloak
    restart: on-failure
    volumes:
      - ./env/KeyCloak/ic-realm.json:/opt/jboss/keycloak/ic-realm.json
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/ic-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=ic-postgres
      - DB_DATABASE=keycloak
      - DB_USER=admin
      - DB_SCHEMA=public
      - DB_PASSWORD=admin
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    depends_on:
      ic-postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080/auth/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 15
    networks:
      - ic-network

  ic-pgadmin:
    image: ic-pgadmin
    container_name: ic-pgadmin
    restart: on-failure
    build: ./env/pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      ic-postgres:
        condition: service_healthy
    ports:
      - 5050:80
    networks:
      - ic-network

  seq:
    image: datalust/seq:latest
    restart: on-failure
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - ic-network

networks:
  ic-network:
    name: ic-network
